name: google
env: 
  token: GITHUB_123
on: 
  workflow_dispatch: {}
  push: 
     branches: 
      - main 
  pull_request:
     branches:
        - main
jobs:
  build:
   runs-on: ubuntu-20.04
   env: 
    token: GITHUB_123
   steps: 
     - name: checkout
       env: 
        token: GITHUB_123
       uses: actions/checkout@v1
       with: 
        password: ${{ env.token }}
     - name: build
       run: |
         npm install
         npm start
     - name: Upload artifact for deployment job ${{  env.token }}
       uses: actions/upload-artifact@v2
       with:
          name: node-app
          path: ./scripts
 

     
