name: google
on: 
  workflow_dispatch: {}
  push: 
     branches: 
      - main 
  pull_request:
     branches:
        - main
jobs:
  build:
   runs-on: ubuntu-20.04
     - name: build website
       run: |
         npm install
         npm start
     - name: Upload artifact for deployment job
       uses: actions/upload-artifact@v2
       with:
          name: node-app
          path: ./scripts
     
